language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
script:
  # Lint
  - python mimic/util/pylint.py .
  # Run tests
  - python -m unittest discover
